# Предположим, что у приложения есть конфигурация
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
stringData:
  {{- range $key, $value := .Values.app.env.secretData }}
  {{ $key }}: {{ $value }}
  {{- end }}
