# Добавим ClusterIP для ingress-controller и для доступа из кластера

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  {{- with .Values.app.container }}
  ports:
    - protocol: TCP
      port: {{ .ports.web }}
      targetPort: {{ .ports.web }}
  {{- end }}
